
//! Autogenerated weights for `tellor`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-09-20, STEPS: `25`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `PAR03017`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/parachain-template-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution
// compiled
// --pallet=tellor
// --extrinsic=*
// --steps=25
// --repeat=10
// --output=../tellor-pallet/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `tellor`.
pub trait WeightInfo {
	fn register() -> Weight;
	fn claim_onetime_tip(t: u32, ) -> Weight;
	fn claim_tip(t: u32, ) -> Weight;
	fn fund_feed() -> Weight;
	fn setup_data_feed(q: u32, ) -> Weight;
	fn tip(q: u32, ) -> Weight;
	fn add_staking_rewards() -> Weight;
	fn submit_value(q: u32, v: u32, ) -> Weight;
	fn update_stake_amount(s: u32, l: u32, ) -> Weight;
	fn begin_dispute(d: u32, ) -> Weight;
	fn vote() -> Weight;
	fn vote_on_multiple_disputes(v: u32, ) -> Weight;
	fn send_votes(v: u32, ) -> Weight;
	fn report_stake_deposited() -> Weight;
	fn report_staking_withdraw_request() -> Weight;
	fn report_stake_withdrawn() -> Weight;
	fn report_slash() -> Weight;
	fn report_vote_tallied() -> Weight;
	fn report_vote_executed(r: u32, ) -> Weight;
	fn on_initialize(s: u32, l: u32, v: u32, ) -> Weight;
}

/// Weights for `tellor` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: System Account (r:4 w:4)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `11402`
		// Minimum execution time: 169_000_000 picoseconds.
		Weight::from_parts(173_000_000, 11402)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Tellor TipCount (r:1 w:0)
	/// Proof: Tellor TipCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:101 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor Tips (r:100 w:100)
	/// Proof: Tellor Tips (max_values: None, max_size: Some(92), added: 2567, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:1)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:0)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:0)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor QueryIdsWithFunding (r:0 w:1)
	/// Proof: Tellor QueryIdsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// The range of component `t` is `[1, 100]`.
	fn claim_onetime_tip(t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `842 + t * (147 ±0)`
		//  Estimated: `8799 + t * (2581 ±0)`
		// Minimum execution time: 146_000_000 picoseconds.
		Weight::from_parts(52_906_000, 8799)
			// Standard Error: 144_480
			.saturating_add(Weight::from_parts(24_958_612, 0).saturating_mul(t.into()))
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_parts(0, 2581).saturating_mul(t.into()))
	}
	/// Storage: Tellor DataFeeds (r:1 w:1)
	/// Proof: Tellor DataFeeds (max_values: None, max_size: Some(138), added: 2613, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:100 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor DataFeedRewardClaimed (r:100 w:100)
	/// Proof: Tellor DataFeedRewardClaimed (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:101 w:0)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:1)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:0)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:0)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor FeedsWithFunding (r:0 w:1)
	/// Proof: Tellor FeedsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// The range of component `t` is `[1, 100]`.
	fn claim_tip(t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1020 + t * (144 ±0)`
		//  Estimated: `8799 + t * (2789 ±0)`
		// Minimum execution time: 146_000_000 picoseconds.
		Weight::from_parts(142_455_120, 8799)
			// Standard Error: 150_889
			.saturating_add(Weight::from_parts(26_041_098, 0).saturating_mul(t.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_parts(0, 2789).saturating_mul(t.into()))
	}
	/// Storage: Tellor DataFeeds (r:1 w:1)
	/// Proof: Tellor DataFeeds (max_values: None, max_size: Some(138), added: 2613, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:1)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor FeedsWithFunding (r:0 w:1)
	/// Proof: Tellor FeedsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	fn fund_feed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `615`
		//  Estimated: `6196`
		// Minimum execution time: 58_000_000 picoseconds.
		Weight::from_parts(59_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Tellor DataFeeds (r:1 w:1)
	/// Proof: Tellor DataFeeds (max_values: None, max_size: Some(138), added: 2613, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:1)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor FeedsWithFunding (r:0 w:1)
	/// Proof: Tellor FeedsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Tellor QueryData (r:0 w:1)
	/// Proof: Tellor QueryData (max_values: None, max_size: Some(1058), added: 3533, mode: MaxEncodedLen)
	/// Storage: Tellor QueryIdFromDataFeedId (r:0 w:1)
	/// Proof: Tellor QueryIdFromDataFeedId (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// The range of component `q` is `[1, 1024]`.
	fn setup_data_feed(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `6196`
		// Minimum execution time: 75_000_000 picoseconds.
		Weight::from_parts(76_863_625, 6196)
			// Standard Error: 447
			.saturating_add(Weight::from_parts(1_672, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: Tellor TipCount (r:1 w:1)
	/// Proof: Tellor TipCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:1)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor QueryIdsWithFunding (r:0 w:1)
	/// Proof: Tellor QueryIdsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Tellor Tips (r:0 w:1)
	/// Proof: Tellor Tips (max_values: None, max_size: Some(92), added: 2567, mode: MaxEncodedLen)
	/// Storage: Tellor QueryData (r:0 w:1)
	/// Proof: Tellor QueryData (max_values: None, max_size: Some(1058), added: 3533, mode: MaxEncodedLen)
	/// The range of component `q` is `[1, 1024]`.
	fn tip(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `6196`
		// Minimum execution time: 74_000_000 picoseconds.
		Weight::from_parts(75_823_657, 6196)
			// Standard Error: 579
			.saturating_add(Weight::from_parts(4_861, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:0)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:0)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:0)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:0 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn add_staking_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `6196`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(62_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Tellor ReportedTimestampCount (r:1 w:1)
	/// Proof: Tellor ReportedTimestampCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:1 w:1)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:1)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor StakerReportsSubmittedByQueryId (r:1 w:1)
	/// Proof: Tellor StakerReportsSubmittedByQueryId (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:0 w:1)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastNewValue (r:0 w:1)
	/// Proof: Tellor TimeOfLastNewValue (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:0 w:1)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// The range of component `q` is `[1, 1024]`.
	/// The range of component `v` is `[1, 256]`.
	fn submit_value(q: u32, v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `419`
		//  Estimated: `3646`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_023_107, 3646)
			// Standard Error: 215
			.saturating_add(Weight::from_parts(1_842, 0).saturating_mul(q.into()))
			// Standard Error: 861
			.saturating_add(Weight::from_parts(2_564, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:2 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:4 w:0)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:2 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:2 w:0)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:1)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeFee (r:1 w:1)
	/// Proof: Tellor DisputeFee (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// The range of component `s` is `[2, 12]`.
	/// The range of component `l` is `[2, 12]`.
	fn update_stake_amount(s: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (324 ±0) + s * (313 ±0)`
		//  Estimated: `11130`
		// Minimum execution time: 221_000_000 picoseconds.
		Weight::from_parts(228_000_000, 11130)
			// Standard Error: 1_581_388
			.saturating_add(Weight::from_parts(4_191_831, 0).saturating_mul(s.into()))
			// Standard Error: 1_581_388
			.saturating_add(Weight::from_parts(7_450_664, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:0)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:99 w:99)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:1 w:1)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeFee (r:1 w:0)
	/// Proof: Tellor DisputeFee (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor OpenDisputesOnId (r:1 w:1)
	/// Proof: Tellor OpenDisputesOnId (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:1 w:1)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:100 w:0)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:1)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:1)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Tellor VoteInfo (r:0 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Tellor PendingVotes (r:0 w:1)
	/// Proof: Tellor PendingVotes (max_values: None, max_size: Some(41), added: 2516, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeIdsByReporter (r:0 w:1)
	/// Proof: Tellor DisputeIdsByReporter (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeInfo (r:0 w:1)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// The range of component `d` is `[1, 100]`.
	fn begin_dispute(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1076 + d * (539 ±0)`
		//  Estimated: `6196 + d * (2529 ±1)`
		// Minimum execution time: 136_000_000 picoseconds.
		Weight::from_parts(121_792_867, 6196)
			// Standard Error: 44_823
			.saturating_add(Weight::from_parts(8_502_405, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(d.into())))
			.saturating_add(T::DbWeight::get().writes(11_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(d.into())))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(d.into()))
	}
	/// Storage: Tellor DisputeInfo (r:1 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:1 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:1 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Tellor Votes (r:1 w:1)
	/// Proof: Tellor Votes (max_values: None, max_size: Some(90), added: 2565, mode: MaxEncodedLen)
	/// Storage: Tellor StakerDetails (r:1 w:0)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:0)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor VoteTallyByAddress (r:1 w:1)
	/// Proof: Tellor VoteTallyByAddress (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1094`
		//  Estimated: `3859`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(37_000_000, 3859)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Tellor DisputeInfo (r:10 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:10 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:10 w:10)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Tellor Votes (r:10 w:10)
	/// Proof: Tellor Votes (max_values: None, max_size: Some(90), added: 2565, mode: MaxEncodedLen)
	/// Storage: Tellor StakerDetails (r:1 w:0)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:0)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor VoteTallyByAddress (r:1 w:1)
	/// Proof: Tellor VoteTallyByAddress (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// The range of component `v` is `[1, 10]`.
	fn vote_on_multiple_disputes(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `744 + v * (387 ±0)`
		//  Estimated: `3646 + v * (2869 ±0)`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(11_803_459, 3646)
			// Standard Error: 118_514
			.saturating_add(Weight::from_parts(26_748_427, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 2869).saturating_mul(v.into()))
	}
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor PendingVotes (r:256 w:245)
	/// Proof: Tellor PendingVotes (max_values: None, max_size: Some(41), added: 2516, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:245 w:245)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `v` is `[1, 255]`.
	fn send_votes(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + v * (713 ±0)`
		//  Estimated: `3707 + v * (2545 ±7)`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3707)
			// Standard Error: 98_868
			.saturating_add(Weight::from_parts(29_775_552, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 2545).saturating_mul(v.into()))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:0)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:0)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:1)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:1)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakers (r:1 w:1)
	/// Proof: Tellor TotalStakers (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn report_stake_deposited() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `410`
		//  Estimated: `6196`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(60_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:0)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:0)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:1)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:1)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakers (r:1 w:1)
	/// Proof: Tellor TotalStakers (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor ToWithdraw (r:1 w:1)
	/// Proof: Tellor ToWithdraw (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	fn report_staking_withdraw_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `410`
		//  Estimated: `6196`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(58_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor ToWithdraw (r:1 w:1)
	/// Proof: Tellor ToWithdraw (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	fn report_stake_withdrawn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `3646`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3646)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:1)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:1)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:0)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor VoteTallyByAddress (r:1 w:0)
	/// Proof: Tellor VoteTallyByAddress (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:1)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakers (r:1 w:1)
	/// Proof: Tellor TotalStakers (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor ToWithdraw (r:1 w:1)
	/// Proof: Tellor ToWithdraw (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	fn report_slash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `899`
		//  Estimated: `6196`
		// Minimum execution time: 70_000_000 picoseconds.
		Weight::from_parts(76_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Tellor VoteRounds (r:1 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:1 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeInfo (r:1 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	fn report_vote_tallied() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1005`
		//  Estimated: `3859`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 3859)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Tellor DisputeInfo (r:1 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:1 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:20 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor OpenDisputesOnId (r:1 w:1)
	/// Proof: Tellor OpenDisputesOnId (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: System Account (r:21 w:21)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `r` is `[1, 20]`.
	fn report_vote_executed(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `991 + r * (351 ±0)`
		//  Estimated: `3859 + r * (2717 ±0)`
		// Minimum execution time: 71_000_000 picoseconds.
		Weight::from_parts(33_833_263, 3859)
			// Standard Error: 118_173
			.saturating_add(Weight::from_parts(40_452_488, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 2717).saturating_mul(r.into()))
	}
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastStakeAmountUpdate (r:1 w:1)
	/// Proof: Tellor LastStakeAmountUpdate (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:2 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:4 w:0)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:2 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:2 w:0)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:1)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeFee (r:1 w:1)
	/// Proof: Tellor DisputeFee (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor PendingVotes (r:4 w:3)
	/// Proof: Tellor PendingVotes (max_values: None, max_size: Some(41), added: 2516, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:3 w:3)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `s` is `[2, 12]`.
	/// The range of component `l` is `[2, 12]`.
	/// The range of component `v` is `[1, 3]`.
	fn on_initialize(s: u32, l: u32, v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (313 ±0) + s * (384 ±0) + v * (722 ±0)`
		//  Estimated: `11130 + l * (290 ±3) + s * (407 ±3) + v * (2717 ±13)`
		// Minimum execution time: 316_000_000 picoseconds.
		Weight::from_parts(236_922_053, 11130)
			// Standard Error: 1_082_190
			.saturating_add(Weight::from_parts(6_253_366, 0).saturating_mul(s.into()))
			// Standard Error: 1_082_190
			.saturating_add(Weight::from_parts(3_013_191, 0).saturating_mul(l.into()))
			// Standard Error: 4_546_881
			.saturating_add(Weight::from_parts(22_146_935, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(18_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 290).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 407).saturating_mul(s.into()))
			.saturating_add(Weight::from_parts(0, 2717).saturating_mul(v.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: System Account (r:4 w:4)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `11402`
		// Minimum execution time: 169_000_000 picoseconds.
		Weight::from_parts(173_000_000, 11402)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Tellor TipCount (r:1 w:0)
	/// Proof: Tellor TipCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:101 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor Tips (r:100 w:100)
	/// Proof: Tellor Tips (max_values: None, max_size: Some(92), added: 2567, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:1)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:0)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:0)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor QueryIdsWithFunding (r:0 w:1)
	/// Proof: Tellor QueryIdsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// The range of component `t` is `[1, 100]`.
	fn claim_onetime_tip(t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `842 + t * (147 ±0)`
		//  Estimated: `8799 + t * (2581 ±0)`
		// Minimum execution time: 146_000_000 picoseconds.
		Weight::from_parts(52_906_000, 8799)
			// Standard Error: 144_480
			.saturating_add(Weight::from_parts(24_958_612, 0).saturating_mul(t.into()))
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_parts(0, 2581).saturating_mul(t.into()))
	}
	/// Storage: Tellor DataFeeds (r:1 w:1)
	/// Proof: Tellor DataFeeds (max_values: None, max_size: Some(138), added: 2613, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:100 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor DataFeedRewardClaimed (r:100 w:100)
	/// Proof: Tellor DataFeedRewardClaimed (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:101 w:0)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:1)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:0)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:0)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor FeedsWithFunding (r:0 w:1)
	/// Proof: Tellor FeedsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// The range of component `t` is `[1, 100]`.
	fn claim_tip(t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1020 + t * (144 ±0)`
		//  Estimated: `8799 + t * (2789 ±0)`
		// Minimum execution time: 146_000_000 picoseconds.
		Weight::from_parts(142_455_120, 8799)
			// Standard Error: 150_889
			.saturating_add(Weight::from_parts(26_041_098, 0).saturating_mul(t.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_parts(0, 2789).saturating_mul(t.into()))
	}
	/// Storage: Tellor DataFeeds (r:1 w:1)
	/// Proof: Tellor DataFeeds (max_values: None, max_size: Some(138), added: 2613, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:1)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor FeedsWithFunding (r:0 w:1)
	/// Proof: Tellor FeedsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	fn fund_feed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `615`
		//  Estimated: `6196`
		// Minimum execution time: 58_000_000 picoseconds.
		Weight::from_parts(59_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Tellor DataFeeds (r:1 w:1)
	/// Proof: Tellor DataFeeds (max_values: None, max_size: Some(138), added: 2613, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:1)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor FeedsWithFunding (r:0 w:1)
	/// Proof: Tellor FeedsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Tellor QueryData (r:0 w:1)
	/// Proof: Tellor QueryData (max_values: None, max_size: Some(1058), added: 3533, mode: MaxEncodedLen)
	/// Storage: Tellor QueryIdFromDataFeedId (r:0 w:1)
	/// Proof: Tellor QueryIdFromDataFeedId (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// The range of component `q` is `[1, 1024]`.
	fn setup_data_feed(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `6196`
		// Minimum execution time: 75_000_000 picoseconds.
		Weight::from_parts(76_863_625, 6196)
			// Standard Error: 447
			.saturating_add(Weight::from_parts(1_672, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: Tellor TipCount (r:1 w:1)
	/// Proof: Tellor TipCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:1)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor QueryIdsWithFunding (r:0 w:1)
	/// Proof: Tellor QueryIdsWithFunding (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
	/// Storage: Tellor Tips (r:0 w:1)
	/// Proof: Tellor Tips (max_values: None, max_size: Some(92), added: 2567, mode: MaxEncodedLen)
	/// Storage: Tellor QueryData (r:0 w:1)
	/// Proof: Tellor QueryData (max_values: None, max_size: Some(1058), added: 3533, mode: MaxEncodedLen)
	/// The range of component `q` is `[1, 1024]`.
	fn tip(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `6196`
		// Minimum execution time: 74_000_000 picoseconds.
		Weight::from_parts(75_823_657, 6196)
			// Standard Error: 579
			.saturating_add(Weight::from_parts(4_861, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:0)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:0)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:0)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:0 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn add_staking_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `6196`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(62_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Tellor ReportedTimestampCount (r:1 w:1)
	/// Proof: Tellor ReportedTimestampCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:1 w:1)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:1)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor StakerReportsSubmittedByQueryId (r:1 w:1)
	/// Proof: Tellor StakerReportsSubmittedByQueryId (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:0 w:1)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastNewValue (r:0 w:1)
	/// Proof: Tellor TimeOfLastNewValue (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:0 w:1)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// The range of component `q` is `[1, 1024]`.
	/// The range of component `v` is `[1, 256]`.
	fn submit_value(q: u32, v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `419`
		//  Estimated: `3646`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_023_107, 3646)
			// Standard Error: 215
			.saturating_add(Weight::from_parts(1_842, 0).saturating_mul(q.into()))
			// Standard Error: 861
			.saturating_add(Weight::from_parts(2_564, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:2 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:4 w:0)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:2 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:2 w:0)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:1)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeFee (r:1 w:1)
	/// Proof: Tellor DisputeFee (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// The range of component `s` is `[2, 12]`.
	/// The range of component `l` is `[2, 12]`.
	fn update_stake_amount(s: u32, l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (324 ±0) + s * (313 ±0)`
		//  Estimated: `11130`
		// Minimum execution time: 221_000_000 picoseconds.
		Weight::from_parts(228_000_000, 11130)
			// Standard Error: 1_581_388
			.saturating_add(Weight::from_parts(4_191_831, 0).saturating_mul(s.into()))
			// Standard Error: 1_581_388
			.saturating_add(Weight::from_parts(7_450_664, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:0)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:99 w:99)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:1 w:1)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeFee (r:1 w:0)
	/// Proof: Tellor DisputeFee (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor OpenDisputesOnId (r:1 w:1)
	/// Proof: Tellor OpenDisputesOnId (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:1 w:1)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:100 w:0)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:1 w:1)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:1)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Tellor VoteInfo (r:0 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Tellor PendingVotes (r:0 w:1)
	/// Proof: Tellor PendingVotes (max_values: None, max_size: Some(41), added: 2516, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeIdsByReporter (r:0 w:1)
	/// Proof: Tellor DisputeIdsByReporter (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeInfo (r:0 w:1)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// The range of component `d` is `[1, 100]`.
	fn begin_dispute(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1076 + d * (539 ±0)`
		//  Estimated: `6196 + d * (2529 ±1)`
		// Minimum execution time: 136_000_000 picoseconds.
		Weight::from_parts(121_792_867, 6196)
			// Standard Error: 44_823
			.saturating_add(Weight::from_parts(8_502_405, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(d.into())))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(d.into())))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(d.into()))
	}
	/// Storage: Tellor DisputeInfo (r:1 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:1 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:1 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Tellor Votes (r:1 w:1)
	/// Proof: Tellor Votes (max_values: None, max_size: Some(90), added: 2565, mode: MaxEncodedLen)
	/// Storage: Tellor StakerDetails (r:1 w:0)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:0)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor VoteTallyByAddress (r:1 w:1)
	/// Proof: Tellor VoteTallyByAddress (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1094`
		//  Estimated: `3859`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(37_000_000, 3859)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Tellor DisputeInfo (r:10 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:10 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:10 w:10)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Tellor Votes (r:10 w:10)
	/// Proof: Tellor Votes (max_values: None, max_size: Some(90), added: 2565, mode: MaxEncodedLen)
	/// Storage: Tellor StakerDetails (r:1 w:0)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Tellor UserTipsTotal (r:1 w:0)
	/// Proof: Tellor UserTipsTotal (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Tellor VoteTallyByAddress (r:1 w:1)
	/// Proof: Tellor VoteTallyByAddress (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// The range of component `v` is `[1, 10]`.
	fn vote_on_multiple_disputes(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `744 + v * (387 ±0)`
		//  Estimated: `3646 + v * (2869 ±0)`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(11_803_459, 3646)
			// Standard Error: 118_514
			.saturating_add(Weight::from_parts(26_748_427, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(v.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 2869).saturating_mul(v.into()))
	}
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor PendingVotes (r:256 w:245)
	/// Proof: Tellor PendingVotes (max_values: None, max_size: Some(41), added: 2516, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:245 w:245)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `v` is `[1, 255]`.
	fn send_votes(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + v * (713 ±0)`
		//  Estimated: `3707 + v * (2545 ±7)`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3707)
			// Standard Error: 98_868
			.saturating_add(Weight::from_parts(29_775_552, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(v.into())))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 2545).saturating_mul(v.into()))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:0)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:0)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:1)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:1)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakers (r:1 w:1)
	/// Proof: Tellor TotalStakers (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn report_stake_deposited() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `410`
		//  Estimated: `6196`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(60_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:0)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:0)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:1)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:1)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakers (r:1 w:1)
	/// Proof: Tellor TotalStakers (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor ToWithdraw (r:1 w:1)
	/// Proof: Tellor ToWithdraw (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	fn report_staking_withdraw_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `410`
		//  Estimated: `6196`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(58_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor ToWithdraw (r:1 w:1)
	/// Proof: Tellor ToWithdraw (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	fn report_stake_withdrawn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `3646`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3646)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Tellor StakerDetails (r:1 w:1)
	/// Proof: Tellor StakerDetails (max_values: None, max_size: Some(181), added: 2656, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TimeOfLastAllocation (r:1 w:1)
	/// Proof: Tellor TimeOfLastAllocation (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakeAmount (r:1 w:1)
	/// Proof: Tellor TotalStakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor RewardRate (r:1 w:1)
	/// Proof: Tellor RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor AccumulatedRewardPerShare (r:1 w:0)
	/// Proof: Tellor AccumulatedRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor VoteCount (r:1 w:0)
	/// Proof: Tellor VoteCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor VoteTallyByAddress (r:1 w:0)
	/// Proof: Tellor VoteTallyByAddress (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tellor TotalRewardDebt (r:1 w:1)
	/// Proof: Tellor TotalRewardDebt (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor TotalStakers (r:1 w:1)
	/// Proof: Tellor TotalStakers (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:0)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor ToWithdraw (r:1 w:1)
	/// Proof: Tellor ToWithdraw (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	fn report_slash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `899`
		//  Estimated: `6196`
		// Minimum execution time: 70_000_000 picoseconds.
		Weight::from_parts(76_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Tellor VoteRounds (r:1 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:1 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeInfo (r:1 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	fn report_vote_tallied() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1005`
		//  Estimated: `3859`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 3859)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Tellor DisputeInfo (r:1 w:0)
	/// Proof: Tellor DisputeInfo (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: Tellor VoteRounds (r:1 w:0)
	/// Proof: Tellor VoteRounds (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:20 w:1)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor OpenDisputesOnId (r:1 w:1)
	/// Proof: Tellor OpenDisputesOnId (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: System Account (r:21 w:21)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// The range of component `r` is `[1, 20]`.
	fn report_vote_executed(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `991 + r * (351 ±0)`
		//  Estimated: `3859 + r * (2717 ±0)`
		// Minimum execution time: 71_000_000 picoseconds.
		Weight::from_parts(33_833_263, 3859)
			// Standard Error: 118_173
			.saturating_add(Weight::from_parts(40_452_488, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(r.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 2717).saturating_mul(r.into()))
	}
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastStakeAmountUpdate (r:1 w:1)
	/// Proof: Tellor LastStakeAmountUpdate (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Tellor LastReportedTimestamp (r:2 w:0)
	/// Proof: Tellor LastReportedTimestamp (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedTimestampsByIndex (r:4 w:0)
	/// Proof: Tellor ReportedTimestampsByIndex (max_values: None, max_size: Some(60), added: 2535, mode: MaxEncodedLen)
	/// Storage: Tellor Reports (r:2 w:0)
	/// Proof: Tellor Reports (max_values: None, max_size: Some(106), added: 2581, mode: MaxEncodedLen)
	/// Storage: Tellor ReportedValuesByTimestamp (r:2 w:0)
	/// Proof: Tellor ReportedValuesByTimestamp (max_values: None, max_size: Some(314), added: 2789, mode: MaxEncodedLen)
	/// Storage: Tellor StakeAmount (r:1 w:1)
	/// Proof: Tellor StakeAmount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Tellor DisputeFee (r:1 w:1)
	/// Proof: Tellor DisputeFee (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Tellor PendingVotes (r:4 w:3)
	/// Proof: Tellor PendingVotes (max_values: None, max_size: Some(41), added: 2516, mode: MaxEncodedLen)
	/// Storage: Tellor VoteInfo (r:3 w:3)
	/// Proof: Tellor VoteInfo (max_values: None, max_size: Some(242), added: 2717, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	/// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	/// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `s` is `[2, 12]`.
	/// The range of component `l` is `[2, 12]`.
	/// The range of component `v` is `[1, 3]`.
	fn on_initialize(s: u32, l: u32, v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + l * (313 ±0) + s * (384 ±0) + v * (722 ±0)`
		//  Estimated: `11130 + l * (290 ±3) + s * (407 ±3) + v * (2717 ±13)`
		// Minimum execution time: 316_000_000 picoseconds.
		Weight::from_parts(236_922_053, 11130)
			// Standard Error: 1_082_190
			.saturating_add(Weight::from_parts(6_253_366, 0).saturating_mul(s.into()))
			// Standard Error: 1_082_190
			.saturating_add(Weight::from_parts(3_013_191, 0).saturating_mul(l.into()))
			// Standard Error: 4_546_881
			.saturating_add(Weight::from_parts(22_146_935, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(18_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(v.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 290).saturating_mul(l.into()))
			.saturating_add(Weight::from_parts(0, 407).saturating_mul(s.into()))
			.saturating_add(Weight::from_parts(0, 2717).saturating_mul(v.into()))
	}
}
