name: Check Set-Up & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the tellor branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: runtime-api # use to check both crates at the same time

    steps:
      - uses: actions/checkout@v3

      - name: Set-Up
        run: sudo apt update && sudo apt install -y git clang curl libssl-dev llvm libudev-dev cmake protobuf-compiler

      # Fail fast: check formatting first as it doesn't require compilation
      - name: Check formatting
        run: |
          cargo fmt --all --check

      - name: Cache Build artefacts
        uses: Swatinem/rust-cache@v2.7.0
        with:
          shared-key: check

      - name: Check Build
        run: |
          cargo check --release --target wasm32-unknown-unknown --no-default-features

      # Run clippy checks (using same arguments as above to re-use built dependencies)
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --release